### ISSUE TITLE
Twitter Image Issue

### ISSUE THREAD

**Issue by Rahat-ch** [Rahat-ch/The_Sylar_Project#11]
Currently when sharing the link on social media sites like Twitter - the social media card is not displaying an image. Please look into the Head component in pages/index.js to implement a fix. 

Acceptance criteria: We should be able to see the hero image displayed in the twitter social sharing card when sharing the link to the site on social media.

**Comment by KhaledSamir** [comment]
I think I know the issue and will be testing the fix and let you know. Should the hero image display only or you wanna add some text to it?

**Comment by KhaledSamir** [comment]
The fix will make something like this for now: 

![The card for your website will look a little something like this!](https://user-images.githubusercontent.com/4302544/102708436-f7170100-4257-11eb-9c3d-6b09b8a922ef.jpeg)

**Comment by Rahat-ch** [comment]
@KhaledSamir this looks great! Feel free to make a pr!

**Comment by KhaledSamir** [comment]
Thanks, done!
