### ISSUE TITLE
Add Husky Precommit Hook

### ISSUE THREAD

**Issue by Rahat-ch** [Rahat-ch/The_Sylar_Project#17]
Add a husky precommit hook for lining:

https://www.npmjs.com/package/husky

We want to make sure that before committing any code up to a repo we run the hook so that all code is properly linted

**Comment by JordanLong1** [comment]
I would like to tackle this if no one else has already @Rahat-ch

**Comment by Rahat-ch** [comment]
@JordanLong1 it's all yours

**Comment by Rahat-ch** [comment]
resolved in #19
