### ISSUE TITLE
Add more resources

### ISSUE THREAD

**Issue by Rahat-ch** [Rahat-ch/The_Sylar_Project#5]
I am one person going through and adding resources. Please feel free to add resources in your local area in order to have more options available. For now this will be done state by state. 

You can add mental health resources in data/usData.js

If adding resources for another country - create a new file and name it data/${country name}.js

Please follow the same formatting as uses in usData.js and indiaData.js

New country pages will be created once there are at least five resources listed in the country

**Comment by zhravan** [comment]
Hi, I have data to be added from India

**Comment by zhravan** [comment]
@Rahat-ch  How shall I add new resources?

**Comment by mdxprograms** [comment]
@Rahat-ch isn't this for US states only? Would probably need a country selection and countries to drill down.

**Comment by Rahat-ch** [comment]
@mdxprograms yea! So what I'm thinking is once there are enough resources for another country then the home page would change to a country selection page so this bit of code could still live on its own as the US page.

**Comment by mdxprograms** [comment]
> @mdxprograms yea! So what I'm thinking is once there are enough resources for another country then the home page would change to a country selection page so this bit of code could still live on its own as the US page. 

That makes sense to me

**Comment by JordanLong1** [comment]
I can add some resources near me here in California, mind if I work on that?

**Comment by Rahat-ch** [comment]
@JordanLong1 yup this one is an open one for everyone - we need as many resources as possible to make this successful :)

**Comment by Rahat-ch** [comment]
no longer will need pr's for resources as form will soon be up
