### ISSUE TITLE
Add Jest/React Testing Library

### ISSUE THREAD

**Issue by Rahat-ch** [Rahat-ch/The_Sylar_Project#6]
Configure React Testing Library and inmplement a small test as an example. Include any documentation for how tests should be run in readme.

**Comment by JordanLong1** [comment]
I would like to work on this @Rahat-ch

**Comment by Rahat-ch** [comment]
Hey @JordanLong1 I'm actually working on this now and adding some tests feel free to grab anything else

**Comment by JordanLong1** [comment]
Ok no worries. I'll look into another issue thanks @Rahat-ch

**Comment by Rahat-ch** [comment]
resolved in #20
