### ISSUE TITLE
Backend Discussion

### ISSUE THREAD

**Issue by Rahat-ch** [Rahat-ch/The_Sylar_Project#8]
At the moment the data is served via an API Route that is just serving a JSON object. I would love thoughts on what might be good for the backend of this project. The current implementation is to make it easy for anyone to fork and use this for their local areas. I would like to keep ease of use if forked to be taken into consideration for whatever the backend ends up becoming.

**Comment by zhravan** [comment]
I can take up this issue up. 
Could you elaborate more on implementation? Are you planning to connect it to DB server or planning to store it in Cloud based Firebase Storage?

**Comment by Rahat-ch** [comment]
@shravan20 Hey! - So this is likely going to be a larger feature to work on. I'm currently thinking some sort of cloud based storage. This is still open to discussion and I'm hoping for a few more folks to chime in before we proceed on this. 

I think whatever ends up happening we would likely need some sort of request form for non coders to be able to add resources that can than be approved by me or someone else I designate that role to.

**Comment by zhravan** [comment]
@Rahat-ch  
We can go with firebase cloud storage, if we are looking into storing only the JSON data. This can be implemented using express.. The React App can be served as static content from the Express App itself.

**Comment by Rahat-ch** [comment]
Current implementation for backend:
Serverless function with Airtable as the DB. For now I've set up the getAllResources route - will be working on a creating resources route for a user submitted form. 

When submitted the data will be saved in a "no approved" state until I review it. Setting up a zappier integration with Airtable so I get an email notification anytime the record is updated.
